Repository 42AGV/webserv, pull requests merged in 2021-11, with the labels that each got.

#110 Improve build speed
  .github/workflows/compile_check.yml
  .github/workflows/integration_test_check.yml
  .github/workflows/utest_check.yml
  Makefile
Labels: enhancement, subtask

#112 Fix SIGPIPE bug
  html/web3/cgi-bin/slow_cgi.py
  html/web3/index.html
  html/web3/slow_cgi.html
Labels: bug

#128 Fix/post path
  CPPLINT.cfg
  srcs/app/http/response/File.cpp
  srcs/app/http/response/post/HttpPostResponse.cpp
  srcs/app/test/integration/webserv_test.py
  srcs/app/utils/Utils.cpp
  srcs/incs/File.hpp
  srcs/incs/HttpPostResponse.hpp
  srcs/incs/Utils.hpp
Labels: bug

#129 Fix tests
  config/default.conf
  html/web3/cgi-bin/hello/hello.py
  html/web3/cgi-bin/hello_form/hello_form.py
  srcs/app/CGI/CGI.cpp
  srcs/app/http/RequestConfig.cpp
  srcs/app/http/response/File.cpp
  srcs/app/http/response/HttpBaseResponse.cpp
  srcs/app/http/response/get/HttpGetResponse.cpp
  srcs/app/test/integration/webserv_test.py
  srcs/incs/CGI.hpp
  srcs/incs/File.hpp
Labels: bug

#121 Fix make re
  Makefile
  srcs/target/common.mk
  srcs/target/generaterules.mk
Labels: bug

#123 Wrapping syscalls
  srcs/app/CGI/CGI.cpp
  srcs/app/CGI/CgiHandler.cpp
  srcs/app/server/Server.cpp
  srcs/app/server/WebServer.cpp
  srcs/app/utils/SyscallWrap.cpp
  srcs/incs/CgiHandler.hpp
  srcs/incs/Server.hpp
  srcs/incs/SyscallWrap.hpp
  srcs/incs/WebServer.hpp
Labels: subtask
